# Generated by Django 4.0.5 on 2022-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='direction',
        ),
        migrations.AddField(
            model_name='doctor',
            name='direction',
            field=models.ManyToManyField(to='api.direction'),
        ),
    ]
