# Generated by Django 4.0.5 on 2022-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_doctor_direction_doctor_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='work_experience',
            field=models.IntegerField(),
        ),
    ]
