# Generated by Django 4.0.5 on 2022-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_doctor_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.ManyToManyField(to='api.direction', verbose_name='Напрямок'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я Доктора"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_experience',
            field=models.IntegerField(max_length=50, verbose_name='Досвід роботи'),
        ),
    ]
