# Generated by Django 4.0.5 on 2022-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_doctor_birthday_alter_doctor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
