# Generated by Django 4.0.5 on 2022-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_direction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='work_experience',
            field=models.IntegerField(verbose_name='Досвід роботи'),
        ),
    ]
